hyperparameters:
  load_model: False
  run: "2024_04_24_11_47_16"
  policy_model_path: "latest_policy.pt"
  optimizer: 'RMSprop'
  lr_policy: 0.001
  momentum: 0.9
  gamma: 0.9
  lambda: 1.0
  ppo_clip: 0.2
  clip_c1: 0.6
  clip_c2: 0.1
  batch_size: 6
  max_trajectory_length: 6
  learn: True