hyperparameters:
  load_model: False
  policy_model_path: None
  value_model_path: None
  optimizer: 'Adam'
  lr_policy: 0.001
  lr_value: 0.0001
  gamma: 0.99
  entropy_coef: 0.05
  ppo_clip: 0.2
  batch_size: 20
  max_trajectory_length: 30
  learn: True
