hyperparameters:
  load_model: False
  run: "2024_05_18_21_09_27"
  policy_model_path: "latest_policy.pt"
  value_model_path: "latest_value.pt"
  optimizer: 'RMSprop'
  lr_policy: 0.001
  lr_value: 0.001
  momentum: 0.9
  gamma: 0.99
  lambda: 1.0
  ppo_clip: 0.2
  clip_c1: 0
  clip_c2: 0.1
  batch_size: 150
  max_trajectory_length: 150
  learn: True