hyperparameters:
  load_model: False
  run: "2024_04_23_02_20_27"
  policy_model_path: "latest_policy.pt"
  value_model_path: "latest_value.pt"
  optimizer: 'RMSprop'
  lr_policy: 0.001
  lr_value: 0.0001
  momentum: 0.9
  gamma: 0.99
  lambda: 0.99
  ppo_clip: 0.2
  clip_c1: 0.6
  clip_c2: 0.1
  batch_size: 16
  max_trajectory_length: 16
  learn: True