hyperparameters:
  load_model: True
  run: "2024_04_21_20_30_57"
  policy_model_path: "latest_policy.pt"
  value_model_path: "latest_value.pt"
  optimizer: 'Adam'
  lr_policy: 0.001
  lr_value: 0.0001
  gamma: 0.99
  entropy_coef: 0.1
  ppo_clip: 0.2
  batch_size: 10
  max_trajectory_length: 10
  learn: True